add cfn-signal

diff --git a/scripts/cdk/rs-raw-ec2.yaml b/scripts/cdk/rs-raw-ec2.yaml
--- a/scripts/cdk/rs-raw-ec2.yaml
+++ b/scripts/cdk/rs-raw-ec2.yaml
@@ -254,8 +254,14 @@ Resources:
         - Key: Name
           Value: RsRawEC2CdkStack/gcrRsDevWorkshopEc2Ec2Instance
       UserData:
-        Fn::Base64: |
+        Fn::Base64: !Sub |
           #!/bin/bash
+          function exitTrap(){
+           exitCode=$?
+           /opt/aws/bin/cfn-signal --stack ${AWS::StackName} --resource gcrRsDevWorkshopEc2Ec2Instance916D1980 --region ${AWS::Region} -e $exitCode || echo 'Failed to send Cloudformation Signal'
+          }
+          trap exitTrap EXIT
+
           set -e
 
           exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
@@ -287,7 +293,7 @@ Resources:
           if [[ $AWS_REGION =~ ^cn.* ]];then
               url_suffix='com.cn'
           fi 
-          repo_name="https://git-codecommit.$AWS_REGION.amazonaws.${url_suffix}/v1/repos/recommender-system-dev-workshop-code"
+          repo_name="https://git-codecommit.$AWS_REGION.amazonaws.$url_suffix/v1/repos/recommender-system-dev-workshop-code"
           echo $repo_name
 
           echo "run git config --global"
@@ -301,7 +307,8 @@ Resources:
 
           if [[ $AWS_REGION =~ ^cn.* ]]; then
               echo "install kubectl and eksctl in $AWS_REGION"
-              curl -o kubectl https://amazon-eks.s3.cn-north-1.amazonaws.com.cn/1.21.2/2021-07-05/bin/linux/amd64/kubectl
+              #curl -o kubectl https://amazon-eks.s3.cn-north-1.amazonaws.com.cn/1.21.2/2021-07-05/bin/linux/amd64/kubectl
+              curl -o kubectl https://aws-gcr-solutions-assets.s3.cn-northwest-1.amazonaws.com.cn/gcr-rs/eks/kubectl
               chmod +x ./kubectl
               mv ./kubectl /usr/local/bin/kubectl
 
@@ -311,12 +318,11 @@ Resources:
 
           else
               echo "install kubectl and eksctl in $AWS_REGION"
-              curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
+              curl -LO https://aws-gcr-rs-sol-workshop-ap-northeast-1-common.s3.ap-northeast-1.amazonaws.com/eks/kubectl
               chmod +x ./kubectl
               mv ./kubectl /usr/local/bin/kubectl
 
-              UNAME=$(uname -s)
-              curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_${UNAME}_amd64.tar.gz" | tar xz -C /tmp
+              curl --silent --location "https://aws-gcr-rs-sol-workshop-ap-northeast-1-common.s3.ap-northeast-1.amazonaws.com/eks/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
               chmod +x /tmp/eksctl
               mv /tmp/eksctl /usr/local/bin
 
@@ -331,11 +337,11 @@ Resources:
           # config AWS ENV
           sudo -u ec2-user -i <<EOS
           echo "set default.region"
-          aws configure set default.region ${AWS_REGION}
+          aws configure set default.region $AWS_REGION
           aws configure get default.region
-          echo "export ACCOUNT_ID=${ACCOUNT_ID}" | tee -a /home/ec2-user/.bash_profile
-          echo "export AWS_REGION=${AWS_REGION}" | tee -a /home/ec2-user/.bash_profile
-          echo "export REGION=${AWS_REGION}" | tee -a /home/ec2-user/.bash_profile
+          echo "export ACCOUNT_ID=$ACCOUNT_ID" | tee -a /home/ec2-user/.bash_profile
+          echo "export AWS_REGION=$AWS_REGION" | tee -a /home/ec2-user/.bash_profile
+          echo "export REGION=$AWS_REGION" | tee -a /home/ec2-user/.bash_profile
 
           mkdir /home/ec2-user/environment
           cd /home/ec2-user/environment
@@ -347,8 +353,8 @@ Resources:
           }
           unzip main.zip
 
-          echo "git clone ${repo_name}"
-          git clone ${repo_name}
+          echo "git clone $repo_name"
+          git clone $repo_name
 
           mv ./recommender-system-dev-workshop-code-main/* ./recommender-system-dev-workshop-code/
 
@@ -371,12 +377,15 @@ Resources:
       - gcrRsDevWorkshopEc2Ec2RoleDefaultPolicy09DC9B37
       - gcrRsDevWorkshopEc2Ec2Role5FA2A265
       - gcrRsDevWorkshopEc2RepositoryDB48BA65
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT10M
     Metadata:
       aws:cdk:path: RsRawEC2CdkStack/gcrRsDevWorkshopEc2Ec2Instance/Resource
   CDKMetadata:
     Type: AWS::CDK::Metadata
     Properties:
-      Analytics: v2:deflate64:H4sIAAAAAAAAE1VRwW6DMAz9lt1pWnqYtNsqDlVPQzD1HoyrpSUxSpxVKOLflwAt3SnP9vN7tpOLkOcfYvf2Ke9uA+1tC2RRhJol3LLiYkpppUZGm4Ivz73nrCDj2HrglKvQkbeACcdCq1iRGbN8v3tVDQkEhL0I5x4S91wWWembTkHtG4OT1ooq8ozfsulwza+5g3MESianJzmBk4mDRuZRMt7lsNgs0YHjTj8aDWc1greKh6Ml308G/xKnuJ40sEjOeMyU1CJUNE80vSXF6SeXFT34paWL6mIbUItAWiuO3diTU0x2mC/3iMZES2d/Pebz8mMsm6girm77m7+L9F1Xp9TGesNKo6jm9w9dTnFQzAEAAA==
+      Analytics: v2:deflate64:H4sIAAAAAAAAE1VQwW7CMAz9lt1DoBw27TbUA+JE1U7cU9dogTauEmeoivrvS1qg7ORn+/nZfpkMWfYpN29f6uZW0FzXQBZlqFjBVeRnUyirOmS0KTl67j2LnIxj64FTrURH3gImHBuNZk1mFNl286oaEggIWxlOPSTuqchF4etWQ+Vrg5PWgkryjN+qbnGpL7WdcwRapU1PcgIHEw+NzL1ivKnhvuae7Tj+9NOhYVEheKt52Fvy/bTgX+EQ31MG7pIzHoVWnQwlzRdNsaB4/bRlQQ9+Yems2zgG1CBQ12mO09iT00x2mJ17ZGOiJdtfzXw6P8a2iSry4ta/2bv8iMZenNYr6w3rDmU5xz+zIEEyzAEAAA==
     Metadata:
       aws:cdk:path: RsRawEC2CdkStack/CDKMetadata/Default
     Condition: CDKMetadataAvailable
